from flask import Flask, request, jsonify
from flask_cors import CORS
from flask_mysqldb import MySQL
import bcrypt
import jwt
import datetime
from config import Config

# Initialize the Flask application
app = Flask(__name__)
app.config.from_object(Config)

# Enable CORS so our React frontend can talk to our API safely
CORS(app)

# Link MySQL to our Flask app using our config values
mysql = MySQL(app)

# ---------------------------------------------------------
# ROUTE 1: USER REGISTRATION (PATIENTS & DOCTORS)
# ---------------------------------------------------------
@app.route('/api/auth/register', methods=['POST'])
def register():
    data = request.json
    email = data.get('email')
    password = data.get('password')
    role = data.get('role')  # Expecting: 'patient' or 'doctor'
    name = data.get('name')

    # Basic Validation
    if not email or not password or not role or not name:
        return jsonify({"error": "All fields are required"}), 400

    # Securely hash the password using bcrypt
    hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt()).decode('utf-8')

    cursor = mysql.connection.cursor()
    try:
        # Step A: Insert into the core users authentication table
        cursor.execute(
            "INSERT INTO users (email, password_hash, role) VALUES (%s, %s, %s)", 
            (email, hashed_password, role)
        )
        user_id = cursor.lastrowid # Grabs the unique ID generated by AUTO_INCREMENT

        # Step B: Insert into profile tables depending on their role
        if role == 'patient':
            cursor.execute("INSERT INTO patients (user_id, name) VALUES (%s, %s)", (user_id, name))
        elif role == 'doctor':
            # Setting default placeholder values for specialization and fee
            cursor.execute(
                "INSERT INTO doctors (user_id, name, specialization, fees) VALUES (%s, %s, 'General Physician', 500.00)", 
                (user_id, name)
            )
        
        mysql.connection.commit()
        return jsonify({"message": "Registration successful!"}), 201

    except Exception as e:
        mysql.connection.rollback() # Undo changes if something goes wrong
        return jsonify({"error": "Email already exists or database error", "details": str(e)}), 400
    finally:
        cursor.close()

# ---------------------------------------------------------
# ROUTE 2: USER LOGIN (GENERATES SECURE JWT TOKEN)
# ---------------------------------------------------------
@app.route('/api/auth/login', methods=['POST'])
def login():
    data = request.json
    email = data.get('email')
    password = data.get('password')

    cursor = mysql.connection.cursor()
    # Fetch user password hash and role matching the email
    cursor.execute("SELECT id, password_hash, role FROM users WHERE email = %s", (email,))
    user = cursor.fetchone()
    cursor.close()

    # If user exists, check if the password matches the hash
    if user and bcrypt.checkpw(password.encode('utf-8'), user[1].encode('utf-8')):
        # Create a JWT token valid for 24 hours
        token = jwt.encode({
            'user_id': user[0],
            'role': user[2],
            'exp': datetime.datetime.utcnow() + datetime.timedelta(hours=24)
        }, app.config['SECRET_KEY'], algorithm='HS256')

        return jsonify({
            "token": token,
            "role": user[2],
            "message": "Login successful!"
        }), 200
    
    return jsonify({"error": "Invalid email or password"}), 401

# ---------------------------------------------------------
# ROUTE 3: GET ALL AVAILABLE DOCTORS (ROBUST POSITION)
# ---------------------------------------------------------
@app.route('/api/doctors', methods=['GET'])
def get_doctors():
    cursor = mysql.connection.cursor()
    try:
        # Simplified query to ensure items populate the frontend seamlessly
        cursor.execute("""
            SELECT id, name, specialization, fees 
            FROM doctors 
            WHERE availability_status = TRUE
        """)
        columns = [col[0] for col in cursor.description]
        doctors = [dict(zip(columns, row)) for row in cursor.fetchall()]
        
        return jsonify(doctors), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()

# ---------------------------------------------------------
# ROUTE 4: BOOK AN APPOINTMENT
# ---------------------------------------------------------
@app.route('/api/appointments/book', methods=['POST'])
def book_appointment():
    data = request.json
    patient_id = data.get('patient_id')  
    doctor_id = data.get('doctor_id')
    appointment_date = data.get('appointment_date') 

    if not patient_id or not doctor_id or not appointment_date:
        return jsonify({"error": "Missing booking details"}), 400

    cursor = mysql.connection.cursor()
    try:
        cursor.execute(
            "INSERT INTO appointments (patient_id, doctor_id, appointment_date, status) VALUES (%s, %s, %s, 'pending')",
            (patient_id, doctor_id, appointment_date)
        )
        mysql.connection.commit()
        return jsonify({"message": "Appointment booked successfully!"}), 201
    except Exception as e:
        mysql.connection.rollback()
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()

# ---------------------------------------------------------
# ROUTE 5: GET APPOINTMENTS FOR A SPECIFIC DOCTOR (UPDATED & MOVED)
# ---------------------------------------------------------
@app.route('/api/doctor/<int:doctor_id>/appointments', methods=['GET'])
def get_doctor_appointments(doctor_id):
    cursor = mysql.connection.cursor()
    try:
        # LEFT JOIN ensures appointments show up even if profiles desync temporarily
        cursor.execute("""
            SELECT a.id, a.appointment_date, a.status, COALESCE(p.name, 'Default Patient') AS patient_name 
            FROM appointments a
            LEFT JOIN patients p ON a.patient_id = p.id
            WHERE a.doctor_id = %s
            ORDER BY a.appointment_date ASC
        """, (doctor_id,))
        
        columns = [col[0] for col in cursor.description]
        appointments = [dict(zip(columns, row)) for row in cursor.fetchall()]
        
        return jsonify(appointments), 200
    except Exception as e:
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()
# ---------------------------------------------------------
# ROUTE 6: UPDATE APPOINTMENT STATUS (ACCEPT/REJECT)
# ---------------------------------------------------------
@app.route('/api/appointments/<int:appointment_id>/status', methods=['PUT'])
def update_appointment_status(appointment_id):
    data = request.json
    new_status = data.get('status') # Expecting: 'accepted' or 'rejected'

    if new_status not in ['accepted', 'rejected']:
        return jsonify({"error": "Invalid status update value"}), 400

    cursor = mysql.connection.cursor()
    try:
        # Update the specific appointment record execution row
        cursor.execute("""
            UPDATE appointments 
            SET status = %s 
            WHERE id = %s
        """, (new_status, appointment_id))
        
        mysql.connection.commit()
        return jsonify({"message": f"Appointment successfully {new_status}!"}), 200
    except Exception as e:
        mysql.connection.rollback()
        return jsonify({"error": str(e)}), 500
    finally:
        cursor.close()

# ---------------------------------------------------------
# EXECUTION ENGINE START (ALWAYS KEEP AT THE ABSOLUTE END)
# ---------------------------------------------------------
if __name__ == '__main__':
    app.run(debug=True, port=5000)